### ISSUE TITLE
Episode Number

### ISSUE THREAD

**Issue by GodDraken** [kodjodevf/mangayomi#87]
### Steps to reproduce

Open up your library and look at the preview for an anime. The number on the top left of the preview does not display the amount of episodes left, but instead just the total number of episodes(not sure if this is a bug or that is what it's meant to be like).

### Expected behavior

I think the number should display the total number of episodes LEFT not the just the total amount of episodes.

### Actual behavior

It displays the total amount of episodes.

### Mangayomi version

0.1.55

### Device

IPhone X

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose).
- [X] I have updated all installed extensions.

**Comment by Ivela183** [comment]
I agree, the same should be added to manga. It would be easier to know when new chapters or episodes comes out when it shows one UNREAD, instead of just looking one by one to see if it came out already. The "total number of episodes/chapters" should be a Badge option in Display to toggle on/off, the same goes for the "number of unread episode/chapter".
